### ISSUE TITLE
action_space.low

### ISSUE THREAD

**Issue by lalagrass** [Anjum48/rl-examples#3]
I found that the bound was defined by action_space.high like this:
self.a_bound = environment.action_space.high

But for the carracing-v0, there are both high and low:
action_space.high = [1. 1. 1.]
action_space.low = [-1. 0. 0.]

**Comment by Anjum48** [comment]
I didn't realise some of these action spaces were asymmetric - thanks for bringing this to my attention. I'll try and fix this soon hopefully

**Comment by Anjum48** [comment]
I replaced it with
```python
self.a_bound = (environment.action_space.high - environment.action_space.low) / 2
```
