### ISSUE TITLE
RunningStats is not defined

### ISSUE THREAD

**Issue by nathanmargaglio** [Anjum48/rl-examples#5]
Throughout the PPO examples, 'RunningStats()' is called despite never being defined.  This prevents the scripts from running as is, and I'm not sure where it is coming from.

**Comment by Anjum48** [comment]
It's defined in `utils.py`. It's on my todo list to import the functions explicitly (instead of using`*`)

**Comment by Anjum48** [comment]
Updated to use explicit imports and updated the README
